# Available variables:
# {prize}
# {winners}
# {ends}
# {hosted-by}

Embed:
  Title: "🎉 Giveaway: {prize} 🎉"
  Description: "> Press the button below to join the giveaway!\n\n> 🎁 Prize: `{prize}`\n> 🏆 Winners: `{winners}`\n> ⏳ Ends: {ends}"
  Color: "#5e99ff"  # Hex color code
  Image: "https://i.imgur.com/ieNkZYm.png" # Recommended Size: 450x103
  CustomThumbnailURL: ""  # Use a custom image URL, leave blank to disable
  Timestamp: true
  Footer:
    Enabled: true
    CustomIconURL: ""  # Use a custom image URL, ONLY WORKS IF TEXT IS NOT BLANK!, Leave blank to disable
    text: "Hosted by: {hosted-by}"

EmbedEnded:
  Title: "🎉 Giveaway Ended: {prize} 🎉"
  Description: "> The giveaway has ended!\n\n> 🎁 **Prize:** `{prize}`\n> 🏆 **Winners:** {winners}\n> 🔢 **Total Entries:** {entries}"
  Color: "#FF6347" # Hex color code
  Image: "" # Optional: Add an image URL here
  CustomThumbnailURL: "" # Optional: Add a thumbnail URL
  Footer:
    Enabled: true
    CustomIconURL: "" # Use a custom image URL, ONLY WORKS IF TEXT IS NOT BLANK!, Leave blank to disable
    text: "Thanks for participating! Hosted by: {hosted-by}"

Button:
  Label: "Enter"
  Style: "Success" # Primary, Secondary, Success, Danger

EntriesButton:
  Label: "Entries: {entries}"
  Style: "Secondary" # Primary, Secondary, Success, Danger


Messages:
  GiveawayCreated: "🎉 The giveaway has been created successfully!"
  GiveawayWinnersAnnouncement: "🎉 Congratulations to the winners of the **{prize}** giveaway!\n🏆 **Winners:** {winners}"
  GiveawayNoWinners: "😔 The **{prize}** giveaway has ended, but no valid winners could be selected! Better luck next time!"
  GiveawayNoEntries: "😔 The **{prize}** giveaway has ended, but no one entered! Better luck next time!"
  GiveawayNotFound: "❌ This giveaway no longer exists."
  AlreadyEntered: "⚠️ You have already entered this giveaway!"
  EntrySuccess: "✅ You have successfully entered the giveaway for **{prize}**! Good luck!"
  EntryError: "❌ An error occurred while entering the giveaway. Please try again later."

Errors:
  NoPermission: "You don't have permission to use this command!"
  InvalidDuration: "Invalid duration format! Use values like 10m, 2h, or 1d."